### PR TITLE
Retries for spontaneous payments

### LINKED ISSUE #1156: Support spontaneous payments in `InvoicePayer`
`InvoicePayer` is stateless, so it will retry failed spontaneous payments when receiving `PaymentPathFailed` events. However, the `InvoicePayer` interface should be expanded to support spontaneous payments given a retry is needed when `ChannelManager::send_spontaneous_payment` returns `Err(PaymentSendFailure::AllFailedRetrySafe)`.

### PR DESCRIPTION
**Pull request by jkczyz**
`InvoicePayer` handles retries not only when handling `PaymentPathFailed` events but also for some types of `PaymentSendFailure` on the initial send. Expand `InvoicePayer`'s interface with a `pay_pubkey` function for spontaneous (keysend) payments. Add a `send_spontaneous_payment` function to the `Payer` trait to support this and implement it for `ChannelManager`.

Closes #1156.

### CODE REVIEW

File: lightning-invoice/src/payment.rs [hunk 1]
```diff
@@ -244,137 +267,158 @@ where
...
 			},
 			Err(PaymentSendFailure::AllFailedRetrySafe(_)) => {
-				self.retry_payment(payment_id, payment_hash, params)
+				self.retry_payment(entry, payment_id, params)
 			},
-			Err(PaymentSendFailure::PartialFailure { results: _, failed_paths_retry, .. }) => {
+			Err(PaymentSendFailure::PartialFailure { failed_paths_retry, .. }) => {
 				if let Some(retry) = failed_paths_retry {
-					self.retry_payment(payment_id, payment_hash, &retry)
+					self.retry_payment(entry, payment_id, &retry)
```
Comment (TheBlueMatt) [inline lightning-invoice/src/payment.rs:421]: While you're here, can you make this branch always return `Ok(())`, for the same reason the equivalent branch in `pay_internal` always returns `Ok(payment_id)`

File: lightning-invoice/src/payment.rs [hunk 2]
```diff
@@ -244,137 +267,158 @@ where
...
 	) -> Result<PaymentId, PaymentError> {
 		debug_assert!(invoice.amount_milli_satoshis().is_some() ^ amount_msats.is_some());
+
 		let payment_hash = PaymentHash(invoice.payment_hash().clone().into_inner());
-		if invoice.is_expired() {
-			log_trace!(self.logger, "Invoice expired prior to first send for payment {}", log_bytes!(payment_hash.0));
+		let mut payment_cache = self.payment_cache.lock().unwrap();
+		let mut entry = match payment_cache.entry(payment_hash) {
+			hash_map::Entry::Occupied(_) => return Err(PaymentError::Invoice("payment pending")),
+			hash_map::Entry::Vacant(_) => look_up_or_insert!(payment_cache, payment_hash),
```
Comment (TheBlueMatt) [inline lightning-invoice/src/payment.rs:283]: This does another map lookup and then matches on the entry, just like here? I believe the macro can be dropped here and the macro removed after in-lining in the one remaining place its used.

**Review by TheBlueMatt — COMMENTED** [review]
All pretty straightforward.

File: lightning-invoice/src/payment.rs (hunk 2 above)
Comment (jkczyz) [reply lightning-invoice/src/payment.rs:283]: There needs to be at least one extra look-up here in order to get an `OccupiedEntry`, though it currently does two more it seems. We really want to call `hash_map::Entry::insert` here since it returns an `OccupiedEntry` and thus wouldn't need any extra look-ups. Unfortunately, that function is experimental. 🙁 

I updated this to insert directly and look-up once more only. Likewise for `pay_pubkey` in a later commit. Also, inlined the macro in `handle_event`.

Comment (TheBlueMatt) [reply lightning-invoice/src/payment.rs]: Can we refactor things in terms of `&mut ` instead of `OccupiedEntry` and do the drop based on return value?

Comment (jkczyz) [reply lightning-invoice/src/payment.rs]: Yeah, though the drop would require another look-up. Probably ok for the error case, I suppose. Would also need to pass the `PaymentHash` around, too.

File: lightning-invoice/src/payment.rs [hunk 3]
```diff
@@ -244,140 +255,178 @@ where
...
+		let first_hops = self.payer.first_hops();
+		let route = self.router.find_route(&payer, &params, Some(&first_hops.iter().collect::<Vec<_>>()), &self.scorer.lock());
+		if route.is_err() {
+			log_trace!(self.logger, "Failed to find a route for payment {}; not retrying (attempts: {})", log_bytes!(payment_hash.0), attempts);
+			return Err(());
 		}
 
-		let retry_res = self.payer.retry_payment(&route.unwrap(), payment_id);
-		match retry_res {
+		match self.payer.retry_payment(&route.unwrap(), payment_id) {
```
Comment (TheBlueMatt) [inline lightning-invoice/src/payment.rs:414]: After staring at it a bit more, I'm not a huge fan of calling this or `send_payment` with the retry counter lock held. I believe we currently only hold the lock during `send_payment`, and ideally we'd avoid it for both.

Comment (jkczyz) [reply lightning-invoice/src/payment.rs:398]: That's fair. Changed to only lock as needed.

File: lightning-invoice/src/payment.rs [hunk 4]
```diff
@@ -244,140 +253,165 @@ where
...
+		let payment_hash = PaymentHash(Sha256::hash(&payment_preimage.0).into_inner());
+		match self.payment_cache.lock().unwrap().entry(payment_hash) {
+			hash_map::Entry::Occupied(_) => return Err(PaymentError::Invoice("payment pending")),
+			hash_map::Entry::Vacant(entry) => entry.insert(0),
+		};
+
+		let params = RouteParameters {
+			payee: Payee::for_keysend(pubkey),
+			final_value_msat: amount_msats,
+			final_cltv_expiry_delta: DEFAULT_MIN_FINAL_CLTV_EXPIRY as u32,
```
Comment (TheBlueMatt) [inline lightning-invoice/src/payment.rs:308]: Technically, keysend users are supposed to provide this explicitly with the pubkey. Technically, keysend is also garbage. If we chose not to expose it, we should at least have a buffer here, as written I'm not sure if you can keysend to LDK lol.

**Review by TheBlueMatt — APPROVED** [review]

File: lightning-invoice/src/payment.rs (hunk 4 above)
Comment (jkczyz) [reply lightning-invoice/src/payment.rs]: Makes sense. Added `final_cltv_expiry_delta` as another parameter.

**Review by TheBlueMatt — APPROVED** [review]

File: lightning-invoice/src/payment.rs [hunk 5]
```diff
@@ -412,25 +447,27 @@ where
...
 				if *rejected_by_dest {
 					log_trace!(self.logger, "Payment {} rejected by destination; not retrying", log_bytes!(payment_hash.0));
 				} else if payment_id.is_none() {
 					log_trace!(self.logger, "Payment {} has no id; not retrying", log_bytes!(payment_hash.0));
-				} else if let Some(params) = retry {
-					if self.retry_payment(payment_id.unwrap(), *payment_hash, params).is_ok() {
+				} else if retry.is_none() {
+					log_trace!(self.logger, "Payment {} missing retry params; not retrying", log_bytes!(payment_hash.0));
+				} else {
+					if self.retry_payment(payment_id.unwrap(), *payment_hash, retry.as_ref().unwrap()).is_ok() {
```
Comment (valentinewallace) [inline lightning-invoice/src/payment.rs:465]: Seems these could be made into 1 line

File: lightning-invoice/src/payment.rs [hunk 6]
```diff
@@ -244,140 +253,166 @@ where
...
 			Err(PaymentSendFailure::PathParameterError(_)) => {
 				log_trace!(self.logger, "Failed to retry for payment {} due to bogus route/payment data, not retrying.", log_bytes!(payment_hash.0));
-				return Err(());
+				Err(())
 			},
 			Err(PaymentSendFailure::AllFailedRetrySafe(_)) => {
 				self.retry_payment(payment_id, payment_hash, params)
 			},
-			Err(PaymentSendFailure::PartialFailure { results: _, failed_paths_retry, .. }) => {
+			Err(PaymentSendFailure::PartialFailure { failed_paths_retry, .. }) => {
```
Comment (valentinewallace) [inline lightning-invoice/src/payment.rs:410]: Do we test the `PartialFailure` send/retry_payment case?

File: lightning-invoice/src/payment.rs [hunk 7]
```diff
@@ -244,140 +253,166 @@ where
...
+				PaymentSendFailure::PathParameterError(_) => Err(e),
+				PaymentSendFailure::AllFailedRetrySafe(_) => {
+					let mut payment_cache = self.payment_cache.lock().unwrap();
+					let retry_count = payment_cache.get_mut(&payment_hash).unwrap();
+					if *retry_count >= self.retry_attempts.0 {
+						Err(e)
+					} else {
+						*retry_count += 1;
+						std::mem::drop(payment_cache);
+						Ok(self.pay_internal(params, payment_hash, send_payment)?)
```
Comment (valentinewallace) [inline lightning-invoice/src/payment.rs:347]: I'd think this would call `self.retry_payment` (though maybe it doesn't make a difference?), maybe a comment as to the reasoning?

**Review by valentinewallace — COMMENTED** [review]
Overall looks good!

File: lightning-invoice/src/payment.rs (hunk 6 above)
Comment (jkczyz) [reply lightning-invoice/src/payment.rs:411]: Looks like we don't! Added another test.

File: lightning-invoice/src/payment.rs (hunk 7 above)
Comment (jkczyz) [reply lightning-invoice/src/payment.rs:348]: We can't call `retry_payment` because we would need to pass it a `RouteParameter`, which is only given for partial failures.

File: lightning-invoice/src/payment.rs [hunk 8]
```diff
@@ -7,7 +7,7 @@
 // You may not use this file except in accordance with one or both of these
 // licenses.
 
-//! A module for paying Lightning invoices.
+//! A module for paying Lightning invoices and sending spontaneous payments.
```
Comment (valentinewallace) [inline lightning-invoice/src/payment.rs:10]: I think there's a few other places that need updating? i.e. the docs above `pub struct InvoicePayer` and a few lines down from here where it says it's a "utility for paying invoices"

File: lightning-invoice/src/payment.rs [hunk 9]
```diff
@@ -244,140 +254,166 @@ where
...
+		let mut payee = Payee::from_node_id(invoice.recover_payee_pub_key())
+			.with_expiry_time(expiry_time_from_unix_epoch(&invoice).as_secs())
+			.with_route_hints(invoice.route_hints());
+		if let Some(features) = invoice.features() {
+			payee = payee.with_features(features.clone());
+		}
+		let params = RouteParameters {
+			payee,
+			final_value_msat: invoice.amount_milli_satoshis().or(amount_msats).unwrap(),
+			final_cltv_expiry_delta: invoice.min_final_cltv_expiry() as u32,
```
Comment (valentinewallace) [inline lightning-invoice/src/payment.rs:282]: I thought `cltv_expiry_delta != cltv_expiry`?

**Review by valentinewallace — COMMENTED** [review]
ACK mod 2 remaining comments :)

File: lightning-invoice/src/payment.rs (hunk 9 above)
Comment (jkczyz) [reply lightning-invoice/src/payment.rs:283]: IIUC, BOLT 11 defines it as a delta but does not name it as such.

**Review by valentinewallace — APPROVED** [review]

**Comment by TheBlueMatt** [comment]
Can you squash fixups?

**Review by TheBlueMatt — APPROVED** [review]
Squash had no diff, will land after CI:

```
$ git diff-tree -U1 c4116fce 592bfd7c
$
```
