### PR TITLE
Be less aggressive in outbound HTLC CLTV timeout checks

### LINKED ISSUE #1114: LDK Refuses to forward when other nodes have aggressive final CLTV Deltas
My public node regularly fails to forward for "CLTV too soon" errors like:

```
INFO  [lightning::ln::channelmanager:1822] Failed to accept/forward incoming HTLC: Outgoing CLTV value is too soon
```

with some additional logging, it looks like the difference from current height to outgoing CLTV height is usually 14 when this happens, implying, I'd guess, that someone is trying to pay an immediate neighbor of mine, with a final CLTV delta of 14 blocks. I'm really not a fan of reducing our "min difference from now" constant down from 21 blocks but there's no way in the current spec to communicate this - we only have the CLTV delta which gates the *inbound* HTLC height, the outbound is entirely based on what the receiving node wants.

### PR DESCRIPTION
**Pull request by TheBlueMatt**
We currently assume our counterparty is naive and misconfigured and
may force-close a channel to get an HTLC we just forwarded them.

There shouldn't be any reason to do this - we don't have any such
bug, and we shouldn't start by assuming our counterparties are
buggy. Worse, this results in refusing to forward payments today,
failing HTLCs for largely no reason.

Instead, we keep a fairly conservative check, but not one which
will fail HTLC forwarding spuriously - testing only that the HTLC
doesn't expire for a few blocks from now.

Fixes #1114.

### CODE REVIEW

File: lightning/src/ln/channelmanager.rs [hunk 1]
```diff
@@ -1850,17 +1850,24 @@ impl<Signer: Sign, M: Deref, T: Deref, K: Deref, F: Deref, L: Deref> ChannelMana
...
-					// In theory, we would be safe against unintentional channel-closure, if we only required a margin of LATENCY_GRACE_PERIOD_BLOCKS.
-					// But, to be safe against policy reception, we use a longer delay.
-					if (*outgoing_cltv_value) as u64 <= (cur_height + HTLC_FAIL_BACK_BUFFER) as u64 {
+					// If the HTLC expires ~now, don't bother trying to forward it to our
+					// counterparty. They should fail it anyway, but we don't want to bother with
+					// the round-trips or risk them deciding they definitely want the HTLC and
+					// force-closing to ensure they get it if we're offline.
+					// We previously had a much more aggressive check here which tried to ensure
+					// our counterparty receives an HTLC which has *our* risk threshold met on it,
+					// but there is no need to do that, and since we're a bit conservative with our
```
Comment (ariard) [inline lightning/src/ln/channelmanager.rs:1868]: I think it can be interesting to dissociate the two different types of risks we're exposed too. The first risk is missing the onchain confirmation of a HTLC on the backward link and as such accounting a loss in our forward HTLC balance. The second risk is the automatic force-close of a channel to achieve the onchain confirmation.

I think what this PR highlights is that we can decrease the latter without affecting the former. Onchain confirmation is function of when the forward link is going to go onchain (`should_broadcast_holder_commitment_tx`) and the CLTV delta between the HTLC on the backward link. None of those values are affected by this change.

However I think we increase our exposure to the second type of risk. In `should_broadcast_holder_commitment_tx`, we decide to go onchain only if an outbound HTLC is _behind_ current height by `LATENCY_GRACE_PERIOD_BLOCKS`. Previously I think we had a buffer of HTLC_FAIL_BACK_BUFFER + LATENCY_GRACE_PERIOD_BLOCKS in the worst-case scenario of forwarding a HTLC with an expiration at the boundary height value. Now, we only have `LATENCY_GRACE_PERIOD_BLOCKS` * 2.

I think this is okay, though if we observe an increase rate of channel force-closed, we could still bump to an intermediary value between `LATENCY_GRACE_PERIOD_BLOCKS` and `HTLC_FAIL_BACK_BUFFER`.

**Review by ariard — COMMENTED** [review]
SGTM, just see comment if we understand the same the risk threshold affected here.

File: lightning/src/ln/channelmanager.rs [hunk 2]
```diff
@@ -1850,17 +1850,24 @@ impl<Signer: Sign, M: Deref, T: Deref, K: Deref, F: Deref, L: Deref> ChannelMana
 						break Some(("Forwarding node has tampered with the intended HTLC values or origin node has an obsolete cltv_expiry_delta", 0x1000 | 13, Some(self.get_channel_update_for_unicast(chan).unwrap())));
 					}
 					let cur_height = self.best_block.read().unwrap().height() + 1;
-					// Theoretically, channel counterparty shouldn't send us a HTLC expiring now, but we want to be robust wrt to counterparty
-					// packet sanitization (see HTLC_FAIL_BACK_BUFFER rational)
+					// Theoretically, channel counterparty shouldn't send us a HTLC expiring now,
+					// but we want to be robust wrt to counterparty packet sanitization (see
+					// HTLC_FAIL_BACK_BUFFER rationale).
 					if msg.cltv_expiry <= cur_height + HTLC_FAIL_BACK_BUFFER as u32 { // expiry_too_soon
 						break Some(("CLTV expiry is too close", 0x1000 | 14, Some(self.get_channel_update_for_unicast(chan).unwrap())));
```
[the remark this answers is not in the document]
Comment (TheBlueMatt) [reply lightning/src/ln/channelmanager.rs:1857]: Yes, I buy that we could drop this check. Doesn't mean we should, of course, but I buy that its actually unreachable. I appreciate the simplicity/readability of a <= and a > check right after each other with straight constants and not having to dig into channel/config code to make sure we don't accidentally do something stupid :)

File: lightning/src/ln/channelmanager.rs (hunk 1 above)
Comment (TheBlueMatt) [reply lightning/src/ln/channelmanager.rs:1868]: Right, I think part of the argument in this PR is that we kinda leave correct handling up to our counterparty. If we give them an HTLC which expires soon they either need to claim it ASAP or fail it ASAP, and probably shouldn't themselves forward it. This is why we use `LATENCY_GRACE_PERIOD_BLOCKS` - its the "we may be desync'd from our peer by this many blocks, so give a bit of a grace period before we do anything drastic" constant.

If our counterparty *does* take a few blocks to fail/claim the HTLC and we have to force-close, I think that speaks more to our counterparty being buggy than us.

Comment (ariard) [reply lightning/src/ln/channelmanager.rs:1868]: Yes, the only cases of non-buggy peers taking more than few blocks to fail/claim the HTLC are hold-invoices or Lightning Rod styles of setup. Though their inflated CLTVs are going to be encompassed within `outgoing_cltv_value` and should not interfere with `LATENCY_GRACE_PERIOD_BLOCKS`.

Comment (TheBlueMatt) [reply lightning/src/ln/channelmanager.rs:1868]: > Yes, the only cases of non-buggy peers taking more than few blocks to fail/claim the HTLC are hold-invoices or Lightning Rod styles of setup. Though their inflated CLTVs are going to be encompassed within outgoing_cltv_value and should not interfere with LATENCY_GRACE_PERIOD_BLOCKS.

I don't think that matters? By the time an invoice gets close to claimable, our counterparty needs to have failed the forwarding end on-chain so that they can do an offchain failure with us. If they don't or if they forward without enough time to do so, then they are buggy, long-CLTV or not.

File: lightning/src/chain/channelmonitor.rs [hunk 3]
```diff
@@ -253,18 +253,13 @@ pub const ANTI_REORG_DELAY: u32 = 6;
 ///    fail this HTLC,
 /// 2) if we receive an HTLC within this many blocks of its expiry (plus one to avoid a race
 ///    condition with the above), we will fail this HTLC without telling the user we received it,
-/// 3) if we are waiting on a connection or a channel state update to send an HTLC to a peer, and
-///    that HTLC expires within this many blocks, we will simply fail the HTLC instead.
```
Comment (valentinewallace) [inline lightning/src/chain/channelmonitor.rs:257]: Are these comment removals related to the main change? The check that was changed doesn't seem related to awaiting on a peer connection/state update..

Comment (TheBlueMatt) [reply lightning/src/chain/channelmonitor.rs:257]: Ah! Good catch - so these two things are really the same thing, but this comment was *actually* referring to a check in `channel` and not in `channelmanager`, even though they're the same check. I've updated the check in channel as well.

Comment (valentinewallace) [reply lightning/src/chain/channelmonitor.rs:257]: Should we mirror this in `ChannelManager::do_chain_event` as well? It still uses `HTLC_FAIL_BACK_BUFFER` to check for timed out HTLCs

**Review by valentinewallace — COMMENTED** [review]
Last two comments I think

File: lightning/src/chain/channelmonitor.rs (hunk 3 above)
Comment (TheBlueMatt) [reply lightning/src/chain/channelmonitor.rs:257]: No, that one is about our own incoming HTLCs, not forwarded ones - that is case `2`.

File: lightning/src/ln/channelmanager.rs [hunk 4]
```diff
@@ -1850,17 +1850,24 @@ impl<Signer: Sign, M: Deref, T: Deref, K: Deref, F: Deref, L: Deref> ChannelMana
 						break Some(("Forwarding node has tampered with the intended HTLC values or origin node has an obsolete cltv_expiry_delta", 0x1000 | 13, Some(self.get_channel_update_for_unicast(chan).unwrap())));
 					}
 					let cur_height = self.best_block.read().unwrap().height() + 1;
-					// Theoretically, channel counterparty shouldn't send us a HTLC expiring now, but we want to be robust wrt to counterparty
-					// packet sanitization (see HTLC_FAIL_BACK_BUFFER rational)
+					// Theoretically, channel counterparty shouldn't send us a HTLC expiring now,
+					// but we want to be robust wrt to counterparty packet sanitization (see
+					// HTLC_FAIL_BACK_BUFFER rationale).
```
[the remark this answers is not in the document]
Comment (TheBlueMatt) [reply lightning/src/ln/channelmanager.rs:1855]: I kinda like keeping it next to the other block count security assumption constants above it? I don't feel super strongly but unless you do I'm not gonna bother moving it.

**Review by valentinewallace — APPROVED** [review]

File: lightning/src/ln/channelmanager.rs (hunk 1 above)
Comment (ariard) [reply lightning/src/ln/channelmanager.rs:1868]: > I don't think that matters?

Yes we agree here, this is what I meant by "should not interfere" :)

**Comment by ariard** [comment]
ACK aaa5c86

**Comment by TheBlueMatt** [comment]
Squashed without diff, will land after CI:

```
$ git diff-tree -U1 aaa5c86b8 5e998cce6
$
```

**Comment by TheBlueMatt** [comment]
Yet again CI passed but GitHub Actions hasn't realized it yet...
