### PR TITLE
Make payments not duplicatively fail/succeed on reload/reconnect

### LINKED ISSUE #209: PaymentSent/PaymentFailed events can be duplicative
This was discovered (and documented) in #208, but its a really terrible API, so should be fixed. I suppose the easy way to do so is to generate these events in response to the commitment_signed dance instead of the initial update_fulfill_htlc message, which I guess is OK, though would be nice to tell the user faster.

### PR DESCRIPTION
**Pull request by TheBlueMatt**
We currently generate duplicative PaymentFailed/PaymentSent events
in two cases:

a) If we receive a update_fulfill_htlc message, followed by a
   disconnect, then a resend of the same update_fulfill_htlc
   message, we will generate a PaymentSent event for each message.

b) When a Channel is closed, any outbound HTLCs which were relayed
   through it are simply dropped when the Channel is. From there,
   the ChannelManager relies on the ChannelMonitor having a copy of
   the relevant fail-/claim-back data and processes the HTLC
   fail/claim when the ChannelMonitor tells it to.

   If, due to an on-chain event, an HTLC is failed/claimed, and
   then we serialize the ChannelManager, but do not re-serialize
   the relevant ChannelMonitor, we may end up getting a duplicative
   event.

In order to provide the expected consistency, we add explicit
tracking of pending outbound payments using their unique
session_priv field which is generated when the payment is sent.
Then, before generating PaymentFailed/PaymentSent events, we check
that the session_priv for the payment is still pending.

Thix fixes #209.

### CODE REVIEW

**Review by valentinewallace — COMMENTED** [review]
Really nice usability improvement. Still reviewing but I think I just have one docs question

File: lightning/src/ln/channelmanager.rs [hunk 1]
```diff
@@ -442,6 +442,17 @@ pub struct ChannelManager<Signer: Sign, M: Deref, T: Deref, K: Deref, F: Deref,
...
 	pending_inbound_payments: Mutex<HashMap<PaymentHash, PendingInboundPayment>>,
 
+	/// The session_priv bytes of outbound payments which are pending resolution.
+	/// The authoritative of these HTLCs resides either within Channels or ChannelMonitors (if the
+	/// channel has been force-closed), however we track them here to prevent duplicative
+	/// PaymentSent/PaymentFailed events. Specifically, in the case of a duplicative
+	/// update_fulfill_htlc message after a reconnect, we may "claim" a payment twice.
+	/// Additionally, for channels which have been force-closed, because the ChannelMonitor event
+	/// is ultimately handled by us, and we aren't supposed to generate duplicative events unless we
+	/// haven't been re-serialized, we have to de-duplicate them here.
```
[the remark this answers is not in the document]
Comment (TheBlueMatt) [reply lightning/src/ln/channelmanager.rs]: I rewrote this section a bit, let me know if its better.

File: lightning/src/ln/channelmanager.rs [hunk 2]
```diff
@@ -2188,17 +2202,23 @@ impl<Signer: Sign, M: Deref, T: Deref, K: Deref, F: Deref, L: Deref> ChannelMana
...
-					self.pending_events.lock().unwrap().push(
-						events::Event::PaymentFailed {
-							payment_hash,
-							rejected_by_dest: false,
+				HTLCSource::OutboundRoute { session_priv, .. } => {
+					if {
+						let mut session_priv_bytes = [0; 32];
+						session_priv_bytes.copy_from_slice(&session_priv[..]);
+						self.outbound_pending_payments.lock().unwrap().remove(&session_priv_bytes)
+					} {
```
Comment (valentinewallace) [inline lightning/src/ln/channelmanager.rs:2210]: Fwiw, I commented these lines out and all tests passed

Comment (TheBlueMatt) [reply lightning/src/ln/channelmanager.rs:2210]: Hmm, indeed, I don't know that its possible to have a duplicate fail issue for an HTLC that was never forwarded as it was in the holding cell. Could add a test which just ensures we dont "leak" any outbound payments, but that's all this does.

File: lightning/src/ln/channelmanager.rs (hunk 1 above)
[the remark this answers is not in the document]
Comment (valentinewallace) [reply lightning/src/ln/channelmanager.rs]: Suggested phrasing: "Additionally, because we don't write out ChannelMonitors after each new block, it's possible that replaying blocks on ChannelMonitors after restart can result in duplicate `update_fulfill_htlc` events coming from force-closed ChannelMonitors."

[the remark this answers is not in the document]
Comment (TheBlueMatt) [reply lightning/src/ln/channelmanager.rs]: Ok, Rewrote it again more similar to what you suggested here. Note that it isn't actually update_fulfill_htlc messages/events.

**Comment by TheBlueMatt** [comment]
Squashed with no diff from `853838c1` to `da33f5c3`

**Review by jkczyz — APPROVED** [review]

**Comment by TheBlueMatt** [comment]
Rebased on latest upstream and added trivial cleanups to address Jeff's comments above. Would like a once-over from one of the existing reviewers.

**Comment by TheBlueMatt** [comment]
Squashed and added one additional commit to address the fuzz failures this introduced.

File: fuzz/src/chanmon_consistency.rs [hunk 3]
```diff
@@ -179,7 +179,7 @@ impl KeysInterface for KeyProvider {
 			SecretKey::from_slice(&[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6, self.node_id]).unwrap(),
 			SecretKey::from_slice(&[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, self.node_id]).unwrap(),
 			SecretKey::from_slice(&[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, self.node_id]).unwrap(),
-			[id, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, self.node_id],
+			[id as u8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, self.node_id],
```
Comment (jkczyz) [inline fuzz/src/chanmon_consistency.rs:182]: I take it we don't need to use four bytes here because we won't exhaust the one-byte space?

**Comment by jkczyz** [comment]
ACK 864375e5f2de5aed94540bc8241ba31484c980e5

Tested locally.

File: fuzz/src/chanmon_consistency.rs (hunk 3 above)
Comment (TheBlueMatt) [reply fuzz/src/chanmon_consistency.rs:182]: Yea, we only ever create up to two of them per peer.
