### PR TITLE
Makes ChannelManager::force_close_channel fail for unknown chan_ids

### LINKED ISSUE #773: ChannelManager::force_close_channel does not fail on random channel_id
`ChannelManager::force_close_channel` attempts to close any given `channel_id`, even if the latter is unknown by the manager.

This contrasts with `ChannelManager::close_channel`, where a `errors::APIError::ChannelUnavailable` will be raised.

Having the same interface regarding unknown channels by both methods feels like the way to go, so I think `force_close_channel` should be updated.

### PR DESCRIPTION
**Pull request by sr-gi**
ChannelManager::force_close_channel does not fail if a non-existing channel id is being passed, making it hard to catch from an API point of view.

Makes force_close_channel return in the same way close_channel does so the user calling the method with an unknown id can be warned.

There's a couple of things that may need fixing:

- There's currently no testing of this anywhere, since I haven't found any unit testing or similar. I can add it if I missed it.
- I was unsure if the c-bindings need to be recreated for every change, or if you do right before a new release.

close #773

### CODE REVIEW

File: lightning/src/ln/channelmanager.rs [hunk 1]
```diff
@@ -941,13 +941,15 @@ impl<ChanSigner: ChannelKeys, M: Deref, T: Deref, K: Deref, F: Deref, L: Deref>
...
+
+		Ok(())
 	}
 
 	/// Force close all channels, immediately broadcasting the latest local commitment transaction
 	/// for each to the chain and rejecting new HTLCs on each.
 	pub fn force_close_all_channels(&self) {
 		for chan in self.list_channels() {
-			self.force_close_channel(&chan.channel_id);
+			self.force_close_channel(&chan.channel_id).unwrap();
```
Comment (TheBlueMatt) [inline lightning/src/ln/channelmanager.rs:952]: This is race-y - if we close a channel in another thread while this is running we'll panic needlessly.

File: lightning/src/ln/channelmanager.rs [hunk 2]
```diff
@@ -918,7 +918,7 @@ impl<ChanSigner: ChannelKeys, M: Deref, T: Deref, K: Deref, F: Deref, L: Deref>
 
 	/// Force closes a channel, immediately broadcasting the latest local commitment transaction to
 	/// the chain and rejecting new HTLCs on the given channel.
-	pub fn force_close_channel(&self, channel_id: &[u8; 32]) {
+	pub fn force_close_channel(&self, channel_id: &[u8; 32]) -> Result<(), APIError>{
```
Comment (TheBlueMatt) [inline lightning/src/ln/channelmanager.rs:921]: It would be nice to update the docs here to state that we only fail in case the channel is not found.

File: lightning/src/ln/channelmanager.rs (hunk 1 above)
Comment (sr-gi) [reply lightning/src/ln/channelmanager.rs]: Rebased in 0e83723

File: lightning/src/ln/channelmanager.rs (hunk 2 above)
Comment (sr-gi) [reply lightning/src/ln/channelmanager.rs:921]: Rebased in 0e83723

File: lightning/src/ln/channelmanager.rs [hunk 3]
```diff
@@ -3471,11 +3473,11 @@ impl<ChanSigner: ChannelKeys, M: Deref + Sync + Send, T: Deref + Sync + Send, K:
 		if msg.channel_id == [0; 32] {
 			for chan in self.list_channels() {
 				if chan.remote_network_id == *counterparty_node_id {
-					self.force_close_channel(&chan.channel_id);
+					self.force_close_channel(&chan.channel_id).unwrap();
 				}
 			}
 		} else {
-			self.force_close_channel(&msg.channel_id);
+			self.force_close_channel(&msg.channel_id).unwrap();
```
Comment (TheBlueMatt) [inline lightning/src/ln/channelmanager.rs:3480]: This handles an untrusted message from a peer - if they send us a garbage channel_id we shouldn't crash.

File: lightning/src/ln/channelmanager.rs [hunk 4]
```diff
@@ -3471,11 +3473,11 @@ impl<ChanSigner: ChannelKeys, M: Deref + Sync + Send, T: Deref + Sync + Send, K:
 		if msg.channel_id == [0; 32] {
 			for chan in self.list_channels() {
 				if chan.remote_network_id == *counterparty_node_id {
-					self.force_close_channel(&chan.channel_id);
+					self.force_close_channel(&chan.channel_id).unwrap();
```
Comment (TheBlueMatt) [inline lightning/src/ln/channelmanager.rs:3476]: This is also race-y, I believe.

File: lightning/src/ln/channelmanager.rs (hunk 3 above)
Comment (sr-gi) [reply lightning/src/ln/channelmanager.rs]: Ups, didn't realize that came from a peer.

Rebased in 03a72f1

File: lightning/src/ln/channelmanager.rs (hunk 4 above)
Comment (sr-gi) [reply lightning/src/ln/channelmanager.rs]: Rebased in 03a72f1

File: lightning/src/ln/channelmanager.rs [hunk 5]
```diff
@@ -3471,11 +3473,11 @@ impl<ChanSigner: ChannelKeys, M: Deref + Sync + Send, T: Deref + Sync + Send, K:
 		if msg.channel_id == [0; 32] {
 			for chan in self.list_channels() {
 				if chan.remote_network_id == *counterparty_node_id {
-					self.force_close_channel(&chan.channel_id);
+					let _ = self.force_close_channel(&msg.channel_id);
```
Comment (ariard) [inline lightning/src/ln/channelmanager.rs:3476]: Can you add a code comment here and below : "Untrusted messages from peer, we throw away the error if id points to a non-existent channel". A good warning to avoid vulns in in case of new work around this code path.

**Review by ariard — COMMENTED** [review]
ACK-modulo-adding-warning-comment.

File: lightning/src/ln/channelmanager.rs (hunk 5 above)
Comment (sr-gi) [reply lightning/src/ln/channelmanager.rs:3477]: Added in 821f6cd
