### PR TITLE
Fix deadlock in ChannelManager's handle_error!()

### LINKED ISSUE #549: Deadlock in handle_error!() on HTLC fail-back
If we hit handle_error!() in ChannelManager, and, at force-close-time, have pending outbound HTLCs in the holding cell, we got to fail them back and will immediately deadlock.

### PR DESCRIPTION
**Pull request by jkczyz**
`ChannelManager` fails backward any pending HTLCs upon channel failure. A deadlock occurs in such cases since `handle_error!()` takes a locked `channel_state` and `finish_force_close_channel()` attempts to reacquire the lock. This PR adds a test to demonstrate the deadlock and fixes it by holding the lock for shorter scopes.

Fixes #549.

### CODE REVIEW

File: lightning/src/ln/functional_tests.rs [hunk 1]
```diff
@@ -2988,6 +2988,77 @@ fn test_commitment_revoked_fail_backward_exhaustive_b() {
...
+			let mut events = nodes[1].node.get_and_clear_pending_msg_events();
+			assert_eq!(events.len(), 1);
+			SendEvent::from_event(events.remove(0))
+		};
+		assert_eq!(payment_event.node_id, nodes[2].node.get_our_node_id());
+		assert_eq!(payment_event.msgs.len(), 1);
+	}
+
+	// Alice -> Bob -> Chuck: Route another payment but now Bob waits for Chuck's earlier revoke_and_ack.
+	let (_, failed_payment_hash) = route_payment(&nodes[0], &[&nodes[1]], 50_000);
```
Comment (TheBlueMatt) [inline lightning/src/ln/functional_tests.rs:3017]: Oh lol, guess you dont need three nodes for this test. Note that this is a completely separate payment from the next one - we disambiguate by HTLCSource, not the payment_hash (as otherwise there are a number of privacy and practical funds issues). The payment_failed at the end is the indicator - its saying that a payment nodes[1] tried to send failed, not that it should fail back the HTLC to nodes[0].

Comment (jkczyz) [reply lightning/src/ln/functional_tests.rs:3017]: Groking: what is "the next one" referring to?

**Comment by TheBlueMatt** [comment]
That was a reference to the manual send_payment call two lines down.

File: lightning/src/ln/functional_tests.rs (hunk 1 above)
Comment (jkczyz) [reply lightning/src/ln/functional_tests.rs:3017]: > That was a reference to the manual send_payment call two lines down.

Ah, I see. This was my attempt at simulating `nodes[2]` not sending `revoke_and_ack`.

If I only need two nodes, then are you saying I can get rid of the `nodes[0]` to `nodes[1]` part entirely (i.e., the places where I'm using `route_payment`)? In that case, what is being "failed backward"?

Comment (TheBlueMatt) [reply lightning/src/ln/functional_tests.rs:3017]: Yep. The part being "failed back" is purely the event telling us that the payment failed (as the lock in question here is taken before we decide if the HTLCSource is an OutboundRoute which we sent or a PreviousHopData which means someone else sent us an HTLC that we relayed).

Comment (jkczyz) [reply lightning/src/ln/functional_tests.rs]: Ok, simplified this by only using two nodes in the test.
