### PR TITLE
Include `height` to `incorrect_or_unknown_payment_details` failure

### LINKED ISSUE #586: Update HTLC error code contents
At least the contents in `incorrect_or_unknown_payment_details` have changed upstream, we should include the latest version and go over our error codes to check that they're all up-to-date. cc https://github.com/rust-bitcoin/rust-lightning/pull/441#discussion_r406561200

### PR DESCRIPTION
**Pull request by D4nte**
Resolves #586.

To prepare the work on this PR, I reviewed all the instantiations of `HTLCFailReason::Reason` against the [latest BOLT spec](https://github.com/lightningnetwork/lightning-rfc/blob/452a0eb916fedf4c954137b4fd0b61b5002b34ad/04-onion-routing.md) and checked whether it includes the spec'd data.

I have not reviewed in details whether or not the failure message was instantiated against the right conditions as the issue only mentioned content.

Edit: I intend to leverage type safety with a follow-up PR as per Matt's [comment](https://github.com/rust-bitcoin/rust-lightning/pull/596#pullrequestreview-396051859).

### CODE REVIEW

File: lightning/src/ln/channelmanager.rs [hunk 1]
```diff
@@ -1733,12 +1733,15 @@ impl<ChanSigner: ChannelKeys, M: Deref, T: Deref, K: Deref, F: Deref> ChannelMan
 									}
 									if total_value >= msgs::MAX_VALUE_MSAT || total_value > data.total_msat  {
 										for htlc in htlcs.iter() {
+											let mut htlc_msat_height_data = byte_utils::be64_to_array(htlc.value).to_vec();
+											let mut height_data = byte_utils::be32_to_array(self.latest_block_height.load(Ordering::Acquire) as u32).to_vec();
+											htlc_msat_height_data.append(&mut height_data);
```
Comment (TheBlueMatt) [inline lightning/src/ln/channelmanager.rs:1738]:
```suggestion
											htlc_msat_height_data.extend_from_slice(&byte_utils::be32_to_array(self.latest_block_height.load(Ordering::Acquire) as u32));
```

No reason for the indirection (plus extra malloc) - 8 bytes on the stack is gonna be way faster than hitting heap.

File: lightning/src/ln/channelmanager.rs [hunk 2]
```diff
@@ -1819,9 +1822,12 @@ impl<ChanSigner: ChannelKeys, M: Deref, T: Deref, K: Deref, F: Deref> ChannelMan
 		if let Some(mut sources) = removed_source {
 			for htlc in sources.drain(..) {
 				if channel_state.is_none() { channel_state = Some(self.channel_state.lock().unwrap()); }
+				let mut htlc_msat_height_data = byte_utils::be64_to_array(htlc.value).to_vec();
+				let mut height_data = byte_utils::be32_to_array(self.latest_block_height.load(Ordering::Acquire) as u32).to_vec();
+				htlc_msat_height_data.append(&mut height_data);
```
Comment (TheBlueMatt) [inline lightning/src/ln/channelmanager.rs:1827]:
```suggestion
											htlc_msat_height_data.extend_from_slice(&byte_utils::be32_to_array(self.latest_block_height.load(Ordering::Acquire) as u32));
```

Same here.

**Comment by D4nte** [comment]
> Yea, in the future we should probably have structs in onion_utils which ensure that we are always passing the right data for each possible error type instead of the ad-hoc stuff right now. Certainly thats a lot more work, so should probably be a separate PR.

Yes it's what I thought. I'll aim to do a follow-up PR that does it. Thanks for the test.

**Comment by TheBlueMatt** [comment]
Hmm, please drop the formatting commit. We'll probably want to do that all in one go (https://github.com/rust-bitcoin/rust-lightning/pull/425), its someone needless churn to do it as we go.

File: lightning/src/ln/channelmanager.rs [hunk 3]
```diff
@@ -1733,12 +1733,19 @@ impl<ChanSigner: ChannelKeys, M: Deref, T: Deref, K: Deref, F: Deref> ChannelMan
 									}
 									if total_value >= msgs::MAX_VALUE_MSAT || total_value > data.total_msat  {
 										for htlc in htlcs.iter() {
+											let mut htlc_msat_height_data = byte_utils::be64_to_array(htlc.value).to_vec();
+											htlc_msat_height_data.extend_from_slice(
+												&byte_utils::be32_to_array(
+													self.latest_block_height.load(Ordering::Acquire)
+														as u32,
```
Comment (TheBlueMatt) [inline lightning/src/ln/channelmanager.rs]: nit: It seems...a bit overkill to have a line just for an "as u32".

**Comment by D4nte** [comment]
> Hmm, please drop the formatting commit. We'll probably want to do that all in one go (#425), its someone needless churn to do it as we go.

Done!
